Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
	config.vm.hostname = "lmatarisS"
	config.vm.provider "virtualbox" do |v|
		v.name = "lmatarisS"
		v.memory = 2048
		v.cpus = 1
	end

	config.vm.network "private_network", ip: "192.168.56.110"
	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		sudo echo "127.0.0.1 $(hostname)" >> /etc/hosts

		export K3S_KUBECONFIG_MODE="644"
		export INSTALL_K3S_EXEC="--flannel-iface=eth1"

		curl -sfL https://get.k3s.io | sh -

		echo "alias k='kubectl'" >> /home/vagrant/.bashrc

		kubectl apply -f /vagrant/deployment/app-one.yaml
		kubectl apply -f /vagrant/deployment/app-two.yaml
		kubectl apply -f /vagrant/deployment/app-three.yaml
		kubectl apply -f /vagrant/deployment/ingress.yaml
	SHELL
end
