Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.provision "shell", inline: <<-SHELL
		export DEBIAN_FRONTEND=noninteractive
		sudo apt-get update -y
		sudo apt-get install net-tools -y
	SHELL

	config.vm.define "acoezardS" do |control|
		control.vm.hostname = "acoezardS"
		control.vm.network "private_network", ip: "192.168.56.110"

		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "acoezardS"]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.memory = 2048
			v.cpus = 1
		end

		control.vm.provision "shell", privileged: true, inline: <<-SHELL
			echo "127.0.0.1 $(hostname)" >> /etc/hosts

			export K3S_KUBECONFIG_MODE="644"
			export INSTALL_K3S_VERSION="v1.22.9+k3s1"
			export INSTALL_K3S_EXEC="server --advertise-address=192.168.56.110 --node-ip=192.168.56.110"

			curl -sfL https://get.k3s.io | sh -

			echo "alias k='kubectl'" >> /home/vagrant/.bashrc

			k apply -f deployment.yaml
		SHELL
	end
end
