Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.define "acoezarS" do |control|
		control.vm.hostname = "acoezarS"
		control.vm.network "private_network", ip: "192.168.56.110"

		control.vm.provider "virtualbox" do |v|
			v.name = "acoezarS"
			v.memory = 2048
			v.cpus = 1
		end

		control.vm.provision "shell", privileged: false, inline: <<-SHELL
			export K3S_KUBECONFIG_MODE="644"
			export K3S_TOKEN="acoezardS_password"
			export KUBECONFIG=/vagrant/k3s.yaml
			export INSTALL_K3S_EXEC="server --advertise-address=192.168.56.110 --node-ip=192.168.56.110"

			curl -sfL https://get.k3s.io | sh -

			echo "alias k='kubectl'" >> /home/vagrant/.bashrc
		SHELL
	end

	config.vm.define "asebrechSW" do |control|
		control.vm.hostname = "asebrechSW"
		control.vm.network "private_network", ip: "192.168.56.111"

		control.vm.provider "virtualbox" do |v|
			v.name = "asebrechSW"
			v.memory = 2048
			v.cpus = 1
		end

		control.vm.provision "shell", privileged: false, inline: <<-SHELL
			export K3S_KUBECONFIG_MODE="644"
			export K3S_URL="https://192.168.56.110:6443"
			export KUBECONFIG=/vagrant/k3s.yaml
			export K3S_TOKEN="acoezardS_password"
			export INSTALL_K3S_EXEC="--node-ip=192.168.56.111"

			curl -sfL https://get.k3s.io | sh -

			echo "alias k='kubectl'" >> /home/vagrant/.bashrc
		SHELL
	end
end
