Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.provision "shell", inline: "sudo dpkg --configure -a"
	config.vm.provision "shell", inline: "sudo apt-get update -y"
	config.vm.provision "shell", inline: "sudo apt-get install net-tools -y"

	config.vm.define "acoezard" do |control|
		control.vm.hostname = "acoezardS"
		control.vm.network "public_network", ip: "192.168.56.110", hostname: true
	end

	config.vm.define "asebrech" do |control|
		control.vm.hostname = "asebrechSW"
		control.vm.network "public_network", ip: "192.168.56.111", hostname: true
	end
end
