Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
	# config.vm.box = "debian/jessie64"
	# config.vm.box_url = "https://app.vagrantup.com/debian/boxes/jessie64"

	config.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update -y
		sudo apt-get install net-tools -y
	SHELL

	config.vm.define "acoezardS" do |control|
		control.vm.hostname = "acoezardS"
		control.vm.network "private_network", ip: "192.168.56.110"

		control.vm.provider "virtualbox" do |v|
			#v.customize ["modifyvm", :id, "--name", "acoezardS"]
			v.memory = 512
			v.cpus = 1
		end
	end

	config.vm.define "asebrechSW" do |control|
		control.vm.hostname = "asebrechSW"
		control.vm.network "private_network", ip: "192.168.56.111"

		control.vm.provider "virtualbox" do |v|
			#v.customize ["modifyvm", :id, "--name", "asebrechSW"]
			v.memory = 512
			v.cpus = 1
		end
	end
end
